---
name: Realtime Builds
on: [push]

jobs:
  #  git_clone:
  #    name: Clone Repository
  #    runs-on: ubuntu-latest
  test_docker_build:
    name: Test Realworld
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Test
        run: pwd && echo ====== && ls -la && echo ====== && env
      - name: Clone test application
        run: git clone --depth 1 $REPO_URL $REPO_DIR
        env:
          REPO_DIR: src
          REPO_URL: https://github.com/gothinkster/node-express-realworld-example-app.git
      - name: Build Docker image
        run: ./test/node-express-realworld-example-app/test.sh
        env:
          DOCKERFILE: Dockerfile
          DOCKER_BASE_IMAGE: node:13.13.0-stretch-slim
          PROJECT: stackuno-node
          REPO_DIR: src
